# GPU
iGPU : 0

# Datasets
sDatabase : 'MRPhysics'

MRPhysics:
  sPathIn : "/med_data/ImageSimilarity/Databases/MRPhysics/newProtocol"
  sSubDir : "dicom_sorted"
  # first entry is always reference, 2nd entry is artifact-affected one
  sPairsMotion:
      HeadT1: ["t1_tse_tra_Kopf_0002", "t1_tse_tra_Kopf_Motion_0003"]
      AbdomenT1: ["t1_tse_tra_fs_mbh_Leber_0004", "t1_tse_tra_fs_mbh_Leber_Motion_0005"]
      AbdomenT2: ["t2_tse_tra_fs_navi_Leber_0006", "t2_tse_tra_fs_navi_Leber_Motion_0013"]
      PelvisT1: ["t1_tse_tra_fs_Becken_0008", "t1_tse_tra_fs_Becken_Motion_0010"]
      PelvisT2: ["t2_tse_tra_fs_Becken_0009", "t2_tse_tra_fs_Becken_Motion_0011"]
  sPairsShim:
      AbdomenT2: ["t2_tse_tra_fs_navi_Leber_0006", "t2_tse_tra_fs_navi_Leber_Shim_xz_0007"]
      PelvisT2: ["t2_tse_tra_fs_Becken_0009", "t2_tse_tra_fs_Becken_Shim_xz_0012"]
  # all classes are marked in JSON file with: 0=no artifact, 1=motion, 2=shim, (-1=unknown artifact)
  sPathInLabel: "/med_data/ImageSimilarity/Databases/MRPhysics/Paper_Markings"

NAKO_IQA:
  sPathIn: "/med_data/ImageSimilarity/Databases/NAKO_IQA"
  sSubDir: "dicom_sorted"
  sPairsMotion:
    WBFBT1: ["3D_GRE_TRA_bh_F_COMPOSED_0014", "3D_GRE_TRA_fb_F_COMPOSED_0028"]
    WBDBT1: ["3D_GRE_TRA_bh_F_COMPOSED_0014", "3D_GRE_TRA_fb_deep_F_COMPOSED_0042"]
  sPathInLabel: "/med_data/ImageSimilarity/Databases/NAKO_IQA_Label"


# network architecture (if existing for chosen database!)
# see *.py files in subfolders of "./networks"
# naming convention: artifactType_bodyRegion_network OR artifactType_network
# artifactType: motion, multiclass
# bodyRegion: abd, head, all
# network: CNN2D, CNN3D, MNetArt, VNetArt
# Single-pathway Multiscale networks are: MS_SPP, MS_FCN_simple, MS_FCN_MultiFM, MS_Inception_Archi1, MS_Inception_Archi2
# Dual-pathway Multiscale networks are: MS_VNet_MultiPath, MS_SPP_MultiPath, MS_FCN_MultiFM_MultiPath
network : "VResFCN_3D_Upsampling_final_Motion_Binary"

# scaling range
range : [0, 1]
# patches
patchSize : [128, 128, 16] # [x, y] or [x,y,z], but z should not larger than 10, else too much zero-padding when scaling factor is small
patchOverlap : 0.8 # 50%
# sLabeling strategy
# 'volume': volume-wise labeling
# 'patch': patch-wise labeling
# 'local': voxel-wise labeling
sLabeling : "local"
# patching strategy
# 'rigidPatching' or'adaptivePatching':
sPatching : "rigidPatching"
# splitting strategy
# 'normal': percentage splitting
# 'crossvalidation_patient': cross validation on patient (leave one patient out)
# 'crossvalidation_data': cross validation on data
sSplitting : "crossvalidation_patient"
# optimized parameters
batchSize : 128
# learning rate
learningRate : 0.001
# amount of epochs
epochs : 100


# paths
# output path
sOutputPath : '/tmp'
